# Initialization

In [1]:
versioninfo()

Julia Version 1.7.3
Commit 742b9abb4d (2022-05-06 12:58 UTC)
Platform Info:
  OS: Linux (x86_64-redhat-linux)
  CPU: Intel(R) Xeon(R) Gold 6226 CPU @ 2.70GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-12.0.1 (ORCJIT, cascadelake)
Environment:
  JULIA_DEPOT_PATH = /home/manabu/.julia-1.7.3
  JULIA_NUM_THREADS = 12


---

In [23]:
using PyCall

In [24]:
using Pkg
Pkg.status("PyCall")

      Status `~/.julia-1.7.3/environments/v1.7/Project.toml`
  [438e738f] PyCall v1.93.1


In [25]:
PyCall.conda

false

In [26]:
PyCall.pyprogramname

"/opt/anaconda3/envs/jupyter/bin/python3"

In [27]:
PyCall.libpython

"/opt/anaconda3/envs/jupyter/lib/libpython3.8.so.1.0"

* [Execution — nlcpy 2.1.1 documentation](https://sxauroratsubasa.sakura.ne.jp/documents/nlcpy/en/usage/execution.html)
  - `VE_NODE_NUMBER`

In [3]:
ENV["VE_NODE_NUMBER"] = "1"

1

In [28]:
np = pyimport("numpy");
vp = pyimport("nlcpy");

In [29]:
np.version.version

"1.23.0"

In [30]:
vp.__version__

"2.1.1"

---

## Typed array literals

* [Multi-dimensional Arrays · The Julia Language](https://docs.julialang.org/en/v1/manual/arrays/#Typed-array-literals)

In [10]:
Float64[1,2]

2-element Vector{Float64}:
 1.0
 2.0

In [13]:
Float64.([1 2;3 4])

2×2 Matrix{Float64}:
 1.0  2.0
 3.0  4.0

### Construction and Initialization
* [Multi-dimensional Arrays · The Julia Language](https://docs.julialang.org/en/v1/manual/arrays/#Construction-and-Initialization)

In [14]:
Array{Float64}([1 2; 3 4])

2×2 Matrix{Float64}:
 1.0  2.0
 3.0  4.0

### slurping `...`

* "What does the `...` operator do?"
  - [Frequently Asked Questions · The Julia Language](https://docs.julialang.org/en/v1/manual/faq/#What-does-the-...-operator-do?)
* "Unpacking Argument Lists" (in Python)
  - [4. More Control Flow Tools — Python 3.10.5 documentation](https://docs.python.org/3/tutorial/controlflow.html#tut-unpacking-arguments)

In [19]:
+((1,2,3)...)

6

In [22]:
x = rand(10^6)
typeof(x)

Vector{Float64} (alias for Array{Float64, 1})