# Float(0)

In [1]:
versioninfo()

Julia Version 1.7.3
Commit 742b9abb4d (2022-05-06 12:58 UTC)
Platform Info:
  OS: Linux (x86_64-redhat-linux)
  CPU: Intel(R) Xeon(R) Gold 6226 CPU @ 2.70GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-12.0.1 (ORCJIT, cascadelake)
Environment:
  JULIA_DEPOT_PATH = /home/manabu/.julia-1.7.3
  JULIA_NUM_THREADS = 12


---

In [2]:
x=AbstractFloat(0)

0.0

In [4]:
typeof(x), supertypes(typeof(x))

(Float64, (Float64, AbstractFloat, Real, Number, Any))

In [11]:
Bool.((Float64(0),Float64(1)))

(false, true)

In [9]:
typeof(NaN)

Float64

In [14]:
try
    Bool(NaN)
catch e
    println(e)
end

InexactError(:Bool, Bool, NaN)


## `Float64` to `bitstring`

* `Base.reinterpret`
  - [Arrays · The Julia Language](https://docs.julialang.org/en/v1/base/arrays/#Base.reinterpret)
  - [parsing - Which is the fastest way to convert an integer to a byte array in Julia - Stack Overflow](https://stackoverflow.com/questions/70781668/which-is-the-fastest-way-to-convert-an-integer-to-a-byte-array-in-julia)
* [Double-precision floating-point format - Wikipedia](https://en.wikipedia.org/wiki/Double-precision_floating-point_format)

* [julia/bitarray.jl at master · JuliaLang/julia](https://github.com/JuliaLang/julia/blob/master/base/bitarray.jl)

In [2]:
Float64(0)

0.0

In [16]:
reinterpret(UInt8, Float64[0])

8-element reinterpret(UInt8, ::Vector{Float64}):
 0x00
 0x00
 0x00
 0x00
 0x00
 0x00
 0x00
 0x00

In [17]:
reinterpret(UInt64, Float64[0])

1-element reinterpret(UInt64, ::Vector{Float64}):
 0x0000000000000000

In [4]:
Float64[0:9;]

10-element Vector{Float64}:
 0.0
 1.0
 2.0
 3.0
 4.0
 5.0
 6.0
 7.0
 8.0
 9.0

In [20]:
reshape(reinterpret(UInt8, Float64[0:9;]),(8,10))

8×10 reshape(reinterpret(UInt8, ::Vector{Float64}), 8, 10) with eltype UInt8:
 0x00  0x00  0x00  0x00  0x00  0x00  0x00  0x00  0x00  0x00
 0x00  0x00  0x00  0x00  0x00  0x00  0x00  0x00  0x00  0x00
 0x00  0x00  0x00  0x00  0x00  0x00  0x00  0x00  0x00  0x00
 0x00  0x00  0x00  0x00  0x00  0x00  0x00  0x00  0x00  0x00
 0x00  0x00  0x00  0x00  0x00  0x00  0x00  0x00  0x00  0x00
 0x00  0x00  0x00  0x00  0x00  0x00  0x00  0x00  0x00  0x00
 0x00  0xf0  0x00  0x08  0x10  0x14  0x18  0x1c  0x20  0x22
 0x00  0x3f  0x40  0x40  0x40  0x40  0x40  0x40  0x40  0x40

In [5]:
reinterpret(UInt64, Float64[0:9;])

10-element reinterpret(UInt64, ::Vector{Float64}):
 0x0000000000000000
 0x3ff0000000000000
 0x4000000000000000
 0x4008000000000000
 0x4010000000000000
 0x4014000000000000
 0x4018000000000000
 0x401c000000000000
 0x4020000000000000
 0x4022000000000000

In [23]:
for x in 0:9
    println(bitstring(reinterpret(UInt64, Float64(x))))
end

0000000000000000000000000000000000000000000000000000000000000000
0011111111110000000000000000000000000000000000000000000000000000
0100000000000000000000000000000000000000000000000000000000000000
0100000000001000000000000000000000000000000000000000000000000000
0100000000010000000000000000000000000000000000000000000000000000
0100000000010100000000000000000000000000000000000000000000000000
0100000000011000000000000000000000000000000000000000000000000000
0100000000011100000000000000000000000000000000000000000000000000
0100000000100000000000000000000000000000000000000000000000000000
0100000000100010000000000000000000000000000000000000000000000000


## `BitVector`

* [julia - Convert an array of UInt64 into a BitVector - Stack Overflow](https://stackoverflow.com/questions/50459690/convert-an-array-of-uint64-into-a-bitvector)
* [I have: Vector{UInt8}. I need: BitVector - General Usage - JuliaLang](https://discourse.julialang.org/t/i-have-vector-uint8-i-need-bitvector/2286)

In [15]:
#x=Array{Bool,1}(undef,64);
#fill!(x,0);

In [52]:
bv = BitVector(zeros(Bool, 64));
bv'

1×64 adjoint(::BitVector) with eltype Bool:
 0  0  0  0  0  0  0  0  0  0  0  0  0  …  0  0  0  0  0  0  0  0  0  0  0  0

In [9]:
bv.chunks[1]=bitreverse(reinterpret(UInt64, Float64(1.41421356)))

0xfbe43ba679056ffc

In [13]:
bv.chunks

1-element Vector{UInt64}:
 0xfbe43ba679056ffc

In [14]:
bitreverse(bv.chunks[1])

0x3ff6a09e65dc27df

In [15]:
join(Int.(bv))

"0011111111110110101000001001111001100101110111000010011111011111"

In [16]:
bs=bitstring(reinterpret(UInt64, Float64(1.41421356)))

"0011111111110110101000001001111001100101110111000010011111011111"

## exponent, significand

In [17]:
bs

"0011111111110110101000001001111001100101110111000010011111011111"

In [337]:
#x = Vector{Char}(bs) .|> (x)->parse(Bool,x);

In [338]:
#x = split(bs,"") .|> (x)->parse(Bool, x);

In [18]:
x=unsafe_wrap(Vector{UInt8}, pointer(bs), ncodeunits(bs)) .|> (x)->parse(Bool, Char(x));

In [19]:
x[2:12]'

1×11 adjoint(::BitVector) with eltype Bool:
 0  1  1  1  1  1  1  1  1  1  1

In [20]:
x[13:end]'

1×52 adjoint(::BitVector) with eltype Bool:
 0  1  1  0  1  0  1  0  0  0  0  0  1  …  0  1  1  1  1  1  0  1  1  1  1  1

In [21]:
using LinearAlgebra

In [22]:
e=dot(x[2:12], (2).^[10:-1:0;]) - 2^10 + 1

0

In [23]:
s=dot(x[13:end], (2.).^[-1:-1:-52;]) + 1

1.41421356

In [24]:
2^e * s

1.41421356

### Julia essentials

In [25]:
Float64[1:9;] |> (x)->(significand.(x), exponent.(x))

([1.0, 1.0, 1.5, 1.0, 1.25, 1.5, 1.75, 1.0, 1.125], [0, 1, 1, 2, 2, 2, 2, 3, 3])

In [26]:
for (s,e) in Float64[1:9;] |> (x)->zip(significand.(x), exponent.(x))
    @show e, s, 2^e*s
end

(e, s, 2 ^ e * s) = (0, 1.0, 1.0)
(e, s, 2 ^ e * s) = (1, 1.0, 2.0)
(e, s, 2 ^ e * s) = (1, 1.5, 3.0)
(e, s, 2 ^ e * s) = (2, 1.0, 4.0)
(e, s, 2 ^ e * s) = (2, 1.25, 5.0)
(e, s, 2 ^ e * s) = (2, 1.5, 6.0)
(e, s, 2 ^ e * s) = (2, 1.75, 7.0)
(e, s, 2 ^ e * s) = (3, 1.0, 8.0)
(e, s, 2 ^ e * s) = (3, 1.125, 9.0)


## Workarounds

* [FAQ: ReinterpretArray vs unsafe_wrap - General Usage - JuliaLang](https://discourse.julialang.org/t/faq-reinterpretarray-vs-unsafe-wrap/14412/2)

### `unsafe_copyto!`

In [32]:
bv = BitVector(zeros(Int8, 64));
bv'

1×64 adjoint(::BitVector) with eltype Bool:
 0  0  0  0  0  0  0  0  0  0  0  0  0  …  0  0  0  0  0  0  0  0  0  0  0  0

In [39]:
#Vector{UInt64}()
c=[bitreverse(reinterpret(UInt64, Float64(3.14)))]
pointer(c), sizeof(c)

(Ptr{UInt64} @0x00007f9d45d76740, 8)

In [40]:
typeof(bv.chunks), pointer(bv.chunks)

(Vector{UInt64}, Ptr{UInt64} @0x00007f9d470cc340)

In [41]:
Base.unsafe_copyto!(pointer(bv.chunks), pointer(c), sizeof(c))
bv.chunks

1-element Vector{UInt64}:
 0xf8a1d78a1d789002

In [46]:
join(Int.(bv))

"0100000000001001000111101011100001010001111010111000010100011111"

### `unsafe_wrap`

In [27]:
bs=bitstring(reinterpret(UInt64, Float64(1.41421356)))

"0011111111110110101000001001111001100101110111000010011111011111"

In [48]:
xs = Vector{Char}(bs)

64-element Vector{Char}:
 '0': ASCII/Unicode U+0030 (category Nd: Number, decimal digit)
 '0': ASCII/Unicode U+0030 (category Nd: Number, decimal digit)
 '1': ASCII/Unicode U+0031 (category Nd: Number, decimal digit)
 '1': ASCII/Unicode U+0031 (category Nd: Number, decimal digit)
 '1': ASCII/Unicode U+0031 (category Nd: Number, decimal digit)
 '1': ASCII/Unicode U+0031 (category Nd: Number, decimal digit)
 '1': ASCII/Unicode U+0031 (category Nd: Number, decimal digit)
 '1': ASCII/Unicode U+0031 (category Nd: Number, decimal digit)
 '1': ASCII/Unicode U+0031 (category Nd: Number, decimal digit)
 '1': ASCII/Unicode U+0031 (category Nd: Number, decimal digit)
 '1': ASCII/Unicode U+0031 (category Nd: Number, decimal digit)
 '1': ASCII/Unicode U+0031 (category Nd: Number, decimal digit)
 '0': ASCII/Unicode U+0030 (category Nd: Number, decimal digit)
 ⋮
 '0': ASCII/Unicode U+0030 (category Nd: Number, decimal digit)
 '1': ASCII/Unicode U+0031 (category Nd: Number, decimal digit)
 '1': ASCII/

In [50]:
xs=unsafe_wrap(Vector{UInt8}, pointer(bs), ncodeunits(bs))

64-element Vector{UInt8}:
 0x30
 0x30
 0x31
 0x31
 0x31
 0x31
 0x31
 0x31
 0x31
 0x31
 0x31
 0x31
 0x30
    ⋮
 0x30
 0x31
 0x31
 0x31
 0x31
 0x31
 0x30
 0x31
 0x31
 0x31
 0x31
 0x31